//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  szkolenia: Szkolenia;
  szkoleniaConnection: SzkoleniaConnection;
  strona: Strona;
  stronaConnection: StronaConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySzkoleniaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySzkoleniaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SzkoleniaFilter>;
};


export type QueryStronaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStronaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StronaFilter>;
};

export type DocumentFilter = {
  szkolenia?: InputMaybe<SzkoleniaFilter>;
  strona?: InputMaybe<StronaFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Szkolenia | Strona | Folder;

export type Szkolenia = Node & Document & {
  __typename?: 'Szkolenia';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  level?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SzkoleniaFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  level?: InputMaybe<StringFilter>;
};

export type SzkoleniaConnectionEdges = {
  __typename?: 'SzkoleniaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Szkolenia>;
};

export type SzkoleniaConnection = Connection & {
  __typename?: 'SzkoleniaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SzkoleniaConnectionEdges>>>;
};

export type Strona = Node & Document & {
  __typename?: 'Strona';
  title: Scalars['String']['output'];
  content?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StronaFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type StronaConnectionEdges = {
  __typename?: 'StronaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Strona>;
};

export type StronaConnection = Connection & {
  __typename?: 'StronaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StronaConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSzkolenia: Szkolenia;
  createSzkolenia: Szkolenia;
  updateStrona: Strona;
  createStrona: Strona;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSzkoleniaArgs = {
  relativePath: Scalars['String']['input'];
  params: SzkoleniaMutation;
};


export type MutationCreateSzkoleniaArgs = {
  relativePath: Scalars['String']['input'];
  params: SzkoleniaMutation;
};


export type MutationUpdateStronaArgs = {
  relativePath: Scalars['String']['input'];
  params: StronaMutation;
};


export type MutationCreateStronaArgs = {
  relativePath: Scalars['String']['input'];
  params: StronaMutation;
};

export type DocumentUpdateMutation = {
  szkolenia?: InputMaybe<SzkoleniaMutation>;
  strona?: InputMaybe<StronaMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  szkolenia?: InputMaybe<SzkoleniaMutation>;
  strona?: InputMaybe<StronaMutation>;
};

export type SzkoleniaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['String']['input']>;
};

export type StronaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type SzkoleniaPartsFragment = { __typename: 'Szkolenia', title: string, subtitle?: string | null, description?: string | null, price?: string | null, duration?: string | null, level?: string | null };

export type StronaPartsFragment = { __typename: 'Strona', title: string, content?: string | null };

export type SzkoleniaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SzkoleniaQuery = { __typename?: 'Query', szkolenia: { __typename: 'Szkolenia', id: string, title: string, subtitle?: string | null, description?: string | null, price?: string | null, duration?: string | null, level?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SzkoleniaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SzkoleniaFilter>;
}>;


export type SzkoleniaConnectionQuery = { __typename?: 'Query', szkoleniaConnection: { __typename?: 'SzkoleniaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SzkoleniaConnectionEdges', cursor: string, node?: { __typename: 'Szkolenia', id: string, title: string, subtitle?: string | null, description?: string | null, price?: string | null, duration?: string | null, level?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StronaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StronaQuery = { __typename?: 'Query', strona: { __typename: 'Strona', id: string, title: string, content?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type StronaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StronaFilter>;
}>;


export type StronaConnectionQuery = { __typename?: 'Query', stronaConnection: { __typename?: 'StronaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StronaConnectionEdges', cursor: string, node?: { __typename: 'Strona', id: string, title: string, content?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SzkoleniaPartsFragmentDoc = gql`
    fragment SzkoleniaParts on Szkolenia {
  __typename
  title
  subtitle
  description
  price
  duration
  level
}
    `;
export const StronaPartsFragmentDoc = gql`
    fragment StronaParts on Strona {
  __typename
  title
  content
}
    `;
export const SzkoleniaDocument = gql`
    query szkolenia($relativePath: String!) {
  szkolenia(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SzkoleniaParts
  }
}
    ${SzkoleniaPartsFragmentDoc}`;
export const SzkoleniaConnectionDocument = gql`
    query szkoleniaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SzkoleniaFilter) {
  szkoleniaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SzkoleniaParts
      }
    }
  }
}
    ${SzkoleniaPartsFragmentDoc}`;
export const StronaDocument = gql`
    query strona($relativePath: String!) {
  strona(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StronaParts
  }
}
    ${StronaPartsFragmentDoc}`;
export const StronaConnectionDocument = gql`
    query stronaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StronaFilter) {
  stronaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StronaParts
      }
    }
  }
}
    ${StronaPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      szkolenia(variables: SzkoleniaQueryVariables, options?: C): Promise<{data: SzkoleniaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SzkoleniaQueryVariables, query: string}> {
        return requester<{data: SzkoleniaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SzkoleniaQueryVariables, query: string}, SzkoleniaQueryVariables>(SzkoleniaDocument, variables, options);
      },
    szkoleniaConnection(variables?: SzkoleniaConnectionQueryVariables, options?: C): Promise<{data: SzkoleniaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SzkoleniaConnectionQueryVariables, query: string}> {
        return requester<{data: SzkoleniaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SzkoleniaConnectionQueryVariables, query: string}, SzkoleniaConnectionQueryVariables>(SzkoleniaConnectionDocument, variables, options);
      },
    strona(variables: StronaQueryVariables, options?: C): Promise<{data: StronaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaQueryVariables, query: string}> {
        return requester<{data: StronaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaQueryVariables, query: string}, StronaQueryVariables>(StronaDocument, variables, options);
      },
    stronaConnection(variables?: StronaConnectionQueryVariables, options?: C): Promise<{data: StronaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaConnectionQueryVariables, query: string}> {
        return requester<{data: StronaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StronaConnectionQueryVariables, query: string}, StronaConnectionQueryVariables>(StronaConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/7c414815-511c-47da-be21-2fc727b6f8ee/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  